# Generated by Django 6.0.6 on 2026-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML'), ('xml', 'XML'), ('xps', 'XPS'), ('docx', 'DOCX'), ('txt', 'TXT'), ('md', 'MD'), ('csv', 'CSV'), ('doc', 'DOC'), ('xlsx', 'XLSX'), ('json', 'JSON'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WEBP'), ('tiff', 'TIFF')], max_length=10, verbose_name='File type'),
        ),
    ]
