# Generated by Django 6.0.6 on 2026-10-05 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_uploadeddocument_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadeddocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='google_drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='source',
            field=models.CharField(choices=[('upload', 'Manual upload'), ('google_drive', 'Google Drive')], db_index=True, default='upload', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='uploadeddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('google_drive_file_id__isnull', False)), fields=('user', 'google_drive_file_id'), name='unique_user_google_drive_file'),
        ),
        migrations.AddConstraint(
            model_name='uploadeddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__isnull', False), ('source', 'upload')), fields=('user', 'file_hash'), name='unique_user_upload_file_hash'),
        ),
    ]
