# Generated by Django 6.0.6 on 2026-08-29 11:45

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('file', models.FileField(upload_to='uploads/documents', verbose_name='Uploaded file')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10, verbose_name='File type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File size')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='File hash')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is processed')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing started at')),
                ('processing_error', models.TextField(blank=True, default='', null=True, verbose_name='Error processing file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded document',
                'verbose_name_plural': 'Uploaded documents',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'file_hash')},
            },
        ),
        migrations.CreateModel(
            name='DocumemtsChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(verbose_name='Chunk text')),
                ('chunk_size', models.IntegerField(default=0, verbose_name='Chunks size')),
                ('chunk_index', models.IntegerField(verbose_name='Chunks index')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='Embedding')),
                ('page_number', models.IntegerField(default=0, verbose_name='Page number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.uploadeddocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document chunk',
                'verbose_name_plural': 'Document chunks',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='rag.uploadeddocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Chat history',
                'verbose_name_plural': 'Chat histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('drive_modified_at', models.DateTimeField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_documents', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_source', to='rag.uploadeddocument')),
            ],
            options={
                'unique_together': {('user', 'drive_file_id')},
            },
        ),
    ]
