# Generated by Django 6.0.6 on 2026-08-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='File hash'),
        ),
    ]
