# Generated by Django 6.0.6 on 2026-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_uploadeddocument_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documemtschunks',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Embedding'),
        ),
    ]
