# Generated by Django 6.0.6 on 2026-08-31 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_uploadeddocument_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.CharField(max_length=255, verbose_name='Google account email')),
                ('google_account_id', models.CharField(max_length=255, verbose_name='Google account ID (sub)')),
                ('access_token_encrypted', models.TextField(verbose_name='Encrypted access token')),
                ('refresh_token_encrypted', models.TextField(verbose_name='Encrypted refresh token')),
                ('token_expiry', models.DateTimeField(verbose_name='Access token expiry')),
                ('scopes', models.TextField(verbose_name='Granted scopes')),
                ('key_version', models.IntegerField(default=1, verbose_name='Encryption key version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Google Drive account',
                'verbose_name_plural': 'Google Drive accounts',
                'db_table': 'google_drive_accounts',
            },
        ),
    ]
