# Generated by Django 6.0.6 on 2026-08-31 09:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_googledriveaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledriveaccount',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='googledriveaccount',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
