# Generated by Django 6.0.6 on 2026-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_documemtschunks_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='processing_error',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Error processing file'),
        ),
    ]
