# Generated by Django 6.0.6 on 2026-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_alter_uploadeddocument_processing_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing started at'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='File name'),
        ),
    ]
