# Generated by Django 6.0.6 on 2026-07-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat history', 'verbose_name_plural': 'Chat histories'},
        ),
    ]
