# Generated by Django 6.0.6 on 2026-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_drivedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivedocument',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
