# Generated by Django 5.2 on 2026-06-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='File name')),
                ('file', models.FileField(upload_to='uploads/documents', verbose_name='Uploaded file')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10, verbose_name='File type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File size')),
                ('is_processed', models.BigIntegerField(default=False, verbose_name='Is processed')),
                ('processing_error', models.TextField(blank=True, default=False, null=True, verbose_name='Error processing file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Uploaded document',
                'verbose_name_plural': 'Uploaded documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumemtsChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(verbose_name='Chunk text')),
                ('chunk_size', models.IntegerField(default=0, verbose_name='Chunks size')),
                ('chunk_index', models.IntegerField(verbose_name='Chunks index')),
                ('embedding', models.JSONField(verbose_name='Embedding')),
                ('page_number', models.IntegerField(default=0, verbose_name='Page number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.uploadeddocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document chunk',
                'verbose_name_plural': 'Document chunks',
                'ordering': ['chunk_index'],
            },
        ),
    ]
