# Generated by Django 6.0.6 on 2026-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is processed'),
        ),
    ]
