# Generated by Django 6.0.6 on 2026-07-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_uploadeddocument_processing_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='rag.uploadeddocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Chat history',
                'verbose_name_plural': 'Chat histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
