# Generated by Django 6.0.6 on 2026-07-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_alter_chathistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('drive_modified_at', models.DateTimeField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_source', to='rag.uploadeddocument')),
            ],
        ),
    ]
