# Generated by Django 6.0.6 on 2026-10-07 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('documents', '0003_alter_uploadeddocument_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConversationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='chat.conversation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_links', to='documents.uploadeddocument')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='documents',
            field=models.ManyToManyField(related_name='conversations', through='chat.ConversationDocument', to='documents.uploadeddocument'),
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.AddConstraint(
            model_name='conversationdocument',
            constraint=models.UniqueConstraint(fields=('conversation', 'document'), name='unique_conversation_document'),
        ),
    ]
